const express = require("express");

const router = express.Router();

const allIngredients = [
  "Apple",
  "Banana",
  "Carrot",
  "Tomato",
  "Potato",
  "Broccoli",
  "Spinach",
  "Lettuce",
  "Cucumber",
  "Onion",
  "Garlic",
  "Ginger",
  "Chicken",
  "Beef",
  "Fish",
  "Egg",
  "Milk",
  "Cheese",
  "Butter",
  "Flour",
  "Sugar",
  "Salt",
  "Pepper",
  "Olive Oil",
  "Soy Sauce",
  "Rice",
  "Pasta",
  "Bread",
  "Cilantro",
  "Basil",
  "Thyme",
  "Rosemary",
  "Oregano",
  "Chili Powder",
  "Cumin",
  "Paprika",
  "Mustard",
  "Ketchup",
  "Mayonnaise",
  "Salsa",
  "Honey",
  "Lemon",
  "Lime",
  "Orange",
  "Coffee",
  "Tea",
  "Avocado",
  "Bell Pepper",
  "Zucchini",
  "Asparagus",
  "Celery",
  "Kale",
  "Eggplant",
  "Mushroom",
  "Artichoke",
  "Pineapple",
  "Strawberry",
  "Blueberry",
  "Raspberry",
  "Blackberry",
  "Watermelon",
  "Grapes",
  "Peach",
  "Plum",
  "Cherry",
  "Cantaloupe",
  "Pomegranate",
  "Kiwi",
  "Papaya",
  "Coconut",
  "Almond",
  "Peanut",
  "Cashew",
  "Walnut",
  "Pecan",
  "Hazelnut",
  "Quinoa",
  "Barley",
  "Couscous",
  "Lentil",
  "Chickpea",
  "Black Bean",
  "Kidney Bean",
  "Lima Bean",
  "Green Bean",
  "Sesame Seeds",
  "Chia Seeds",
  "Sunflower Seeds",
  "Pumpkin Seeds",
  "Flaxseed",
  "Popcorn",
  "Cinnamon",
  "Nutmeg",
  "Vanilla Extract",
  "Turmeric",
  "Coriander",
  "Cardamom",
  "Cloves",
  "Dill",
  "Fennel",
  "Tarragon",
  "Bay Leaf",
  "Maple Syrup",
  "Agave Nectar",
  "Molasses",
  "Balsamic Vinegar",
  "Red Wine Vinegar",
  "White Wine Vinegar",
  "Apple Cider Vinegar",
  "Worcestershire Sauce",
  "Sesame Oil",
  "Balsamic Glaze",
  "Fish Sauce",
  "Mirin",
  "Tahini",
  // Add more ingredients as needed
];

router.get("/api/ingredients", (req, res) => {
  res.json(allIngredients);
});

module.exports = router;
